services:
  ml_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8071
    volumes:
      - ./:/home/django/ml_service
    ports:
      - "8071:8071"
    networks:
      - ml_service_network

networks:
  ml_service_network:
    external: true
